name: Enviar E-mail Diariamente

on:
  workflow_dispatch

jobs:
  import-data:
    runs-on: ubuntu-latest
    environment: my_env
    steps:        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

        - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::gmailr

        - name: Checkout do repositório
        uses: actions/checkout@v2

        - name: Enviar e-mail
        working-directory: .github/workflows
        env:
          MEU_EMAIL: ${{ secrets.MEU_EMAIL }}
          SEU_EMAIL: ${{ secrets.SEU_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          options(
            gargle_oauth_cache = ".secret",
            gargle_oauth_email = Sys.getenv("MEU_EMAIL")
          );
          gm_auth_configure(key = Sys.getenv("CLIENT_ID"), secret = Sys.getenv("CLIENT_SECRET"));
          gm_auth(email = Sys.getenv("MEU_EMAIL"));

          mensagem <- "Teste";

          arquivo <- "rato.jpg" |> file.path();

          msg <- gm_mime() |> gm_from(Sys.getenv("MEU_EMAIL")) |>
            gm_to(Sys.getenv("SEU_EMAIL")) |> gm_text_body(mensagem) |>
            gm_attach_file(arquivo);

          gm_send_message(msg);

