name: Enviar E-mail Diariamente

on:
  schedule:
    - cron: '*/1 * * * *' # Executa todos os dias às 20h

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente R
        uses: r-lib/actions/setup-r@v1

      - name: Instalar pacotes
        run: install.packages("gmailr")

      - name: Enviar e-mail
        run: |
          Rscript -e 'library(gmailr);
                      gm_auth_configure(path = Sys.getenv("MEU_EMAIL"));
                      meu_email <- Sys.getenv("MEU_EMAIL");
                      seu_email <- Sys.getenv("SEU_EMAIL");
                      mensagem <- "Teste";
                      arquivo <- "rato.jpg";
                      msg <- gm_mime() |> gm_from(meu_email) |>
                             gm_to(seu_email) |> gm_text_body(mensagem) |>
                             gm_attach_file(arquivo);
                      gm_send_message(msg);'
