name: Enviar E-mail Diariamente

on:
  workflow_dispatch

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::gmailr

      - name: Enviar e-mail
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MEU_EMAIL: ${{ secrets.MEU_EMAIL }}
          SEU_EMAIL: ${{ secrets.SEU_EMAIL }}
        run: |
          Rscript -e 'library(gmailr);
                      id <- Sys.getenv("CLIENT_ID");
                      secret <- Sys.getenv("CLIENT_SECRET");
                      meu_email <- Sys.getenv("MEU_EMAIL");
                      seu_email <- Sys.getenv("SEU_EMAIL");
                      print(id);
                      print(secret);
                      print(meu_email);
                      print(Sys.getenv());
                      gm_auth_configure(key = id, secret = secret);
                      mensagem <- "Teste";
                      arquivo <- "rato.jpg";
                      msg <- gm_mime() |> gm_from(meu_email) |>
                             gm_to(seu_email) |> gm_text_body(mensagem) |>
                             gm_attach_file(arquivo);
                      gm_send_message(msg);'
